language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "lts/*"
script:
  - npm run lint:test
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
